### ISSUE TITLE
Examples in the v1.6 features of using ion-ion binary collisions, `getDFtype4species1`, `getDFtype4InjectedParticles`, and particle output

### ISSUE THREAD

**Issue by weipengyao** [dusse/AKA52#20]
Since v1.6, AKA is able to 

- use ion-ion binary collisions, and play with the `coulomb_log` parameter (?)
- use rectangular distribution function for ions, via `getDFtype4species1` and `getDFtype4InjectedParticles `
- output particle information, e.g., the energy spectrum

Yet, how exactly should the user take advantage of these new features is not clear. 

It would be great if related examples can be provided (e.g., on top of the attached input file). 

Thanks. 

[Initializer.py.txt](https://github.com/dusse/AKA52/files/9481322/Initializer.py.txt)

**Comment by weipengyao** [comment]
A short summary from Andrey's reply:

- Set `getDFtype4species1` and `getDFtype4InjectedParticles` to be `1`, so that the corresponding particle specie has a distribution function of rectangular shape.

- to use particle output one needs to rebuild code with flag/s `-DWRITE_PARTICLES` and/or `-DWRITE_LEFT_PARTICLES`

- for ion-ion collisions, one needs to add two functions:

```
def getDefaultColoumbLogarithm(self):
        return 10

def getIonIonCollisionFrequencyFactor(self):
       return 1.
```

In fact, they are multiplied by each other. So, it is one parameter and this parameter regulates collision frequency.

**Comment by dusse** [comment]
cannot reproduce on local machine, there are no problems with output for your example file,
could you specify which python do you use and which versions for mpi and hdf5?

guess, you have zeros because of getDFandLimits function,
check if you have zeros in original h5 files
<img width="734" alt="example" src="https://user-images.githubusercontent.com/56974475/188443488-5f4500ef-722f-4bcb-bde2-fe482e3c5631.png">

in output files, particles are stored in 1d array,
each particle has 7 numbers: 0 - type, 1-3 - coordinate and 4-6 - velocities.
so, check getDFandLimits function for vmax and ptype

**Comment by weipengyao** [comment]
The example input file does not have the v1.6 features yet. Could you try this one instead to check if you can reproduce the issue?
[Initializer.py.txt](https://github.com/dusse/AKA52/files/9489652/Initializer.py.txt)


the results of the original h5 files give the following:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/37392893/188446334-7794371d-0b61-477a-8440-82e2751e0dd9.png">

**Comment by dusse** [comment]
this one also runs well,
could you try with 1 or 2 cores to check whether it is an mpi problem?

**Comment by weipengyao** [comment]
Yes, with 2 cores, it runs fine. No more stuck and it is still running now. 

```
l
total 36M
-rw-r----- 1 weipeng anticipa 1.2M Sep  5 08:34 free_2d_0.h5
-rw-r----- 1 weipeng anticipa 8.9M Sep  5 08:34 free_2d_particles_0.h5
-rw-r----- 1 weipeng anticipa 1.2M Sep  5 08:37 free_2d_1.h5
-rw-r----- 1 weipeng anticipa  11M Sep  5 08:37 free_2d_particles_1.h5
-rw-r----- 1 weipeng anticipa  46K Sep  5 08:37 free_2d_left_particles_1.h5
-rw-r----- 1 weipeng anticipa 1.2M Sep  5 08:41 free_2d_2.h5
-rw-r----- 1 weipeng anticipa  12M Sep  5 08:41 free_2d_particles_2.h5
-rw-r----- 1 weipeng anticipa  88K Sep  5 08:41 free_2d_left_particles_2.h5
```

I will check later about the post-processing of the particle data when I have more late-time results.

Thanks.

**Comment by dusse** [comment]
def getDFandLimits(filePath, xleft, xright):

    particlesNum = getParticlesNumber(filePath)
    particles = loadFullParticles(filePath, 0, particlesNum)
    vmax = 1.5
    beansNum = 100
    df1 = np.zeros([beansNum])
    df2 = np.zeros([beansNum])

    for prtcl in particles:
        ptype = prtcl[0]
        enrgy = prtcl[4]**2
    
        if ptype == 0:
            beanNum = int((enrgy)/(vmax**2) * beansNum)
            if beanNum < beansNum: 
                df1[beanNum] += 1
        if ptype == 2:
            beanNum = int((enrgy)/((vmax**2)) * beansNum)
            if beanNum < beansNum: 
                df2[beanNum] += 1
            else:
                print('v = ', np.sqrt(enrgy))
                
    return [df1, df2, beansNum, vmax]


so it checks for two types 0 and 2
and the maximum velocity is 1.5 not 20,
in you problem the average velocity is around 1 and maximum is around 1.5

**Comment by dusse** [comment]
so, i have succeeded to reproduce your stuck.
seems, it is because of writing left particles and MPI_Allgather, need to analyze deeper.
there are two options now:
1. use only -DWRITE_PARTICLES
2. do not use more than 2 core per a side

**Comment by dusse** [comment]
it is fixed, check please.

**Comment by weipengyao** [comment]
> it is fixed, check please.

Yes, now the code can be run with 8x4 cores on Niagara within 8 min.

```
[0] [1] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
[0] [1] *****************************************************.
[0] [1] ****                                             ****.
[0] [1] ****          FINISH SIMULATION                  ****.
[0] [1] **** Total duration for 4001 steps : 8 min.
[0] [1] ****                                             ****.
[0] [1] *****************************************************.
[0] [2] [SimulationManager] finalize...OK.
[0] [2] [Loader] FINALIZE...OK!.
```

**Comment by weipengyao** [comment]
After change the `vmax` in the function `getDFandLimits` from 20 to 1.5, the results are no longer just zeros, and I can plot something like below:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/37392893/189056689-edbd67f2-d8b9-4b77-96e7-d4f242121030.png">

But the question is, for the four lines, they correspond to outputs of:
```
outputs = ['free_2d_particles_1.h5','free_2d_left_particles_5.h5','free_2d_left_particles_7.h5','free_2d_left_particles_10.h5']
```
But the 2nd and 3rd one are still all zero. 

Then I checked the ten outputs for left particles one-by-one and I found only the 9th and 10th have value, and it is increasing. 
<img width="518" alt="image" src="https://user-images.githubusercontent.com/37392893/189058041-ae7ce367-8744-4dbf-b42e-f8e099f0a339.png">

Is this normal? 

Besides, when calculating the energy of the particles, the use of 
```
for prtcl in particles:
        ptype = prtcl[0]
        enrgy = prtcl[4]**2
```
is just for illustration, and we need to use all three velocities (4-7) and `E = 0.5*m*v**2`, right?

**Comment by weipengyao** [comment]
In fact, I realize that after the function `loadFullParticles`, we get all the particle information, and we can start to do whatever we want with them. 

The use of the function `getDFandLimits` is not necessary.

However, a clarification of the units for the positions and velocities is needed. 

And type 0 is the ions initialized in the simulation box, type 2 is the injected one, right? -- meaning that only at the 9th and 10th time, the particles are starting to get injected?

Thanks!

**Comment by weipengyao** [comment]
the particle information at the beginning and end of the simulation shows:
![spectra](https://user-images.githubusercontent.com/37392893/189667576-1e302c0e-b14e-458d-ae12-6d77bc30eb28.png)

So no particular change for the particle travelling through the plasmas.
