### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Afftar123** [dusse/AKA52#5]
Hello! You've already answered this issue, but in another PC there's the same problem I cannot solve
After mpirun -n 2 aka.exe (and, actually, any number of cores) I've got
`
[0] [1] ***********************************************************.
[0] [1] ****                                                   ****.
[0] [1] ****     START  2020-09-29 22:42:04                    ****.
[0] [1] ****                                                   ****.
[0] [1] ****       O        0  A       A         55555  2222   ****.
[0] [1] ****      O O       O  A      A A        5          2  ****.
[0] [1] ****     O   O      O A      A   A       5          2  ****.
[0] [1] ****    OOOOOOO     0A      AAAAAAA      5555    2222  ****.
[0] [1] ****   O       0    O A    A       A         5  2      ****.
[0] [1] ****  O         O   O  A  A         A    55555  22222  ****.
[0] [1] ****   Arbitrary  Kinetic  Algorithm                   ****.
[0] [1] ***********************************************************.
[0] [0] [SimulationManager] ATTENTION!!! used default input file path src/input/ !!!.
[0] [0] [SimulationManager] ATTENTION!!! used default input file path src/input/ !!!.
[ubuntu:322278] *** Process received signal ***
[ubuntu:322278] Signal: Segmentation fault (11)
[ubuntu:322278] Signal code: Address not mapped (1)
[ubuntu:322278] Failing at address: 0x8
[ubuntu:322278] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f732e3ef210]
[ubuntu:322278] [ 1] /lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyModule_GetDict+0xb)[0x7f732f162f7b]
[ubuntu:322278] [ 2] aka.exe(+0x1ff73)[0x55dbac9c3f73]
[ubuntu:322278] [ 3] aka.exe(+0x20740)[0x55dbac9c4740]
[ubuntu:322278] [ 4] aka.exe(+0xbfa4)[0x55dbac9affa4]
[ubuntu:322278] [ 5] aka.exe(+0xe8d1)[0x55dbac9b28d1]
[ubuntu:322278] [ 6] aka.exe(+0xa87b)[0x55dbac9ae87b]
[ubuntu:322278] [ 7] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f732e3d00b3]
[ubuntu:322278] [ 8] aka.exe(+0xa94e)[0x55dbac9ae94e]
[ubuntu:322278] *** End of error message ***
[ubuntu:322279] *** Process received signal ***
[ubuntu:322279] Signal: Segmentation fault (11)
[ubuntu:322279] Signal code: Address not mapped (1)
[ubuntu:322279] Failing at address: 0x8
[ubuntu:322279] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7fdb22ba9210]
[ubuntu:322279] [ 1] /lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyModule_GetDict+0xb)[0x7fdb2391cf7b]
[ubuntu:322279] [ 2] aka.exe(+0x1ff73)[0x55a69a7c3f73]
[ubuntu:322279] [ 3] aka.exe(+0x20740)[0x55a69a7c4740]
[ubuntu:322279] [ 4] aka.exe(+0xbfa4)[0x55a69a7affa4]
[ubuntu:322279] [ 5] aka.exe(+0xe8d1)[0x55a69a7b28d1]
[ubuntu:322279] [ 6] aka.exe(+0xa87b)[0x55a69a7ae87b]
[ubuntu:322279] [ 7] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fdb22b8a0b3]
[ubuntu:322279] [ 8] aka.exe(+0xa94e)[0x55a69a7ae94e]
[ubuntu:322279] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node ubuntu exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
`
Tried to reinstall openmpi (use 4.0.5) and hdf5 (use 1.12.0) but it didn't help

**Comment by dusse** [comment]
hello my friend!
could you check the last update.
normally, if you see smth associated with python 
like: gnu/libpython2.7.so.1.0(PyModule_GetDict+0xb)[0x7fdb2391cf7b]
it means you should check the input file.
there are two class of problems with python files in context of AKA52 use:
1. in input file user has problems with indents (critical for python)
2. in input file user asks for imports but have not cared about python environment variables

in the updated version all imports have been removed from default input file and it has no indent problems.
